galaxy_info:
  role_name: systemd_journald
  author: Companies House
  description: Provision systemd-journald storage mode
  license: MIT
  min_ansible_version: 2.9.10
  galaxy_tags:
    - systemd
    - journald
  standalone: false
