---

- name: Prerequisite - Check if oracle user exists
  ansible.builtin.getent:
    database: passwd
    key: oracle
  register: oracle_user

- name: Check if Netapp Snapcenter plugin is installed
  ansible.builtin.stat:
    path: "{{ snapcenter_path }}"
  register: snapcenter_plugin

- name: Install Netapp Snapcenter
  ansible.builtin.include_tasks: snapcenter.yml
  when: not snapcenter_plugin.stat.exists and oracle_user.exists
