---

- name: Create /opt/Netapp/ directory
  ansible.builtin.file:
    path: "{{ netapp_snapcenter_plugin_netapp_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
    register: netapp_dir_result

- name: Download netapp snapcenter plugin from S3
  ansible.builtin.command: aws s3 cp "{{ netapp_snapcenter_plugin_snapcenter_s3_loc }}" "{{ netapp_snapcenter_plugin_netapp_dir_result.path }}"

- name: Make install file executeable
  ansible.builtin.file:
    path: "{{ netapp_snapcenter_plugin_netapp_dir_result.path }}"
    state: file
    recurse: true
    owner: root
    group: root
    mode: "0744"

- name: Get Snapcenter FQDN from Vault
  block:
    - name: Set vault path for lookup
      ansible.builtin.set_fact:
        fqdn_lookup_vault_path: "{{ netapp_snapcenter_plugin_vault_base_path }}/fqdn"

    - name: Retrieve Snapcenter FQDN from Hashicorp vault
      ansible.builtin.set_fact:
        snapcenter_fqdn: "{{ lookup('community.hashi_vault.hashi_vault', fqdn_lookup_vault_path) }}"

- name: Install Netapp Snapcenter plugin
  ansible.bultin.shell: ./snapcenter_linux_host_plugin.bin -i silent -DPORT=8145 -DSERVER_IP='{{ snapcenter_fqdn }}' -DSERVER_HTTPS_PORT=8146
  args:
    chdir: "{{ netapp_snapcenter_plugin_netapp_dir_result.path }}"
  when: not snapcenter_plugin.stat.exists
  register: snapcenter_plugin_install_cmd
  changed_when: snapcenter_plugin_cmd.rc = 0

- name: Copy output to log file
  ansible.builtin.copy:
    content: "{{ snapcenter_plugin_install_cmd.stdout }}"
    dest: "{{ snapcenter_install_log }}"
    owner: root
    group: root
    mode: "0644"
  delegate_to: localhost

- name: Add snapcenter install dir to PATH
  ansible.builtin.copy:
    dest: /etc/profile.d/snapcenter_path.sh
    content: 'PATH=$PATH:(( netapp_snapcenter_plugin_snapcenter_path }}'
    owner: root
    group: root
    mode: "0644"

- name: Check if Netapp Snapcenter service is enabled and active
  ansible.builtin.service:
    name: spl
    enabled: true
    state: started
