---

- name: Create temporary directory
  ansible.builtin.tempfile:
    path: "{{ snapcenter_temp_dir }}"
    state: directory
  register: snapcenter_temp_dir_result
  
- name: Download netapp snapcenter plugin from S3
  ansible.builtin.command: aws s3 cp "{{ snapcenter_s3_loc }}" "{{ snapcenter_temp_dir_result.path }}" 

- name: Make install file executeable
  ansible.builtin.file:
    path: "{{ snapcenter_temp_dir_result.path }}"
    state: file
    recurse: yes
    owner: root
    group: root
    mode: "0755"
  
- name: Install Netapp Snapcenter plugin
  ansible.bultin.shell: ./snapcenter_linux_host_plugin.bin -i silent-DPORT=8145-DSERVER_IP=SnapCenter_Server_FQDN-DSERVER_HTTPS_PORT=SnapCenter_Server_Port-DUSER_INSTALL_DIR==/opt/custom_path
  args:
    chdir: "{{ snapcenter_temp_dir_result.path }}"
  when: not snapcenter_plugin.stat.exists
  register: snapcenter_plugin_install_cmd
  changed_when: snapcenter_plugin_cmd.rc = 0

add expect stuff above here


- name: Enable Netapp Snapcenter service
  ansible.builtin.service:
    name: spl
    enabled: yes

- name: Check Snapcenter installation
  ansible.builtin.shell: systemctl is-active spl.service
  register: spl_service_status
  

- name: Remove temporary directory
  ansible.builtin.file:
    path: "{{ snapcenter_temp_dir_result.path }}"
    state: absent
