---

- name: Create temporary directory
  ansible.builtin.tempfile:
    path: "{{ aws_cli_temp_dir }}"
    state: directory
  register: aws_cli_temp_dir_result

- name: Extract AWS CLI installer to temporary directory
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ aws_cli_url }}"
    dest: "{{ aws_cli_temp_dir_result.path }}"

- name: Install AWS CLI # noqa command-instead-of-shell
  ansible.builtin.shell: ./install
  args:
    chdir: "{{ aws_cli_temp_dir_result.path }}/aws"
  when: not aws_cli.stat.exists
  register: aws_cli_install_cmd
  changed_when: aws_cli_install_cmd.rc == 0

- name: Update existing AWS CLI # noqa command-instead-of-shell
  ansible.builtin.shell: ./install --update
  args:
    chdir: "{{ aws_cli_temp_dir_result.path }}/aws"
  when: aws_cli.stat.exists
  register: aws_cli_update_cmd
  changed_when: aws_cli_update_cmd.rc == 0

- name: Remove temporary directory
  ansible.builtin.file:
    path: "{{ aws_cli_temp_dir_result.path }}"
    state: absent
