---

- name: Check if AWS CLI is installed
  ansible.builtin.stat:
    path: "{{ aws_cli_path }}"
  register: aws_cli

- name: Install or update AWS CLI
  ansible.builtin.include_tasks: awscli.yml
  when: not aws_cli.stat.exists or aws_cli_update
