---

- name: Check for valid mode of operation
  ansible.builtin.assert:
    that:
      - ssh_key_action == "install" or ssh_key_action == "remove"
    msg: "Unsupported value provided for 'ssh_key_action'; specify either 'install' or 'remove'"

- name: Set SSH directory path prefix fact
  ansible.builtin.set_fact:
    ssh_dir_prefix: "{{ '/home' if ssh_key_dir_owner != 'root' }}"

- name: Set SSH directory path fact
  ansible.builtin.set_fact:
    ssh_dir_path: "{{ ssh_dir_prefix }}/{{ ssh_key_dir_owner }}/.ssh"

- name: Set SSH key path fact
  ansible.builtin.set_fact:
    ssh_key_path: "{{ ssh_dir_path }}/{{ ssh_key_name }}"

- name: Install SSH key
  ansible.builtin.include_tasks: create.yml
  when: ssh_key_action == "install"

- name: Remove SSH key
  ansible.builtin.include_tasks: remove.yml
  when: ssh_key_action == "remove"
