---
netapp_snapcenter_plugin_user: oracle
netapp_snapcenter_plugin_snapcenter_path: /opt/NetApp/snapcenter/spl/bin/spl
netapp_snapcenter_plugin_netapp_dir: /opt/NetApp/

netapp_snapcenter_plugin_s3_bucket: /aws-accounts/shared-services/s3/resources_bucket_name
netapp_snapcenter_plugin_s3_bucket_path: /applications/shared-service-eu-west-2/netapp/snapcenter/plugin/plugin_dir
netapp_snapcenter_plugin_file: snapcenter_linux_host_plugin.bin

netapp_snapcenter_plugin_fqdn_vault_path: /applications/shared-services-eu-west-2/netapp/snapcenter/plugin/fqdn






